name: Workshop 1 - Date Workflow  

on:
  push: 
    branches: [workshop1] 
    paths: 
      - 'workshop1/**'
      - '.github/workflows/workflow.yml'  
  pull_request: 
    branches: [workshop1]
    paths: 
      - 'workshop1/**'
      - '.github/workflows/workflow.yml' 
  workflow_dispatch:

jobs:
  imprimir_info:  
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v4  

      - name: Imprimir Mensaje Personalizado
        run: |
          echo "Hola, soy Santiago Gallego - ${{ github.actor }} y este es mi primer workflow!"  
          echo "La fecha y hora actual es: $(date)"  

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.9 

      - name: Ejecutar Script Python
        id: run_script
        run: |  
          mkdir build_output
          python3.12 workshop1/script.py > build_output/output.txt
      
      - name: Subir Artefactos Construidos
        uses: actions/upload-artifact@v4
        with:
          name: script_output_workshop1
          path: build_output